- name: Copy Logstash Config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Start Logstash Service
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: Wait for Logstash Service to Start
  ansible.builtin.wait_for:
    host: logstash.roboshop.internal
    port: 5044
    delay: 30
    timeout: 60
    active_connection_states: [ "LISTEN" ]
  register: out
  ignore_errors: true

- name: debug
  debug:
    msg: "{{out}}"



